In [ ]:
import numpy as np



Vamos a cargar el array de numpy seleccionando las 5 primeras columnas manualmente para evitar problemas con los separadores.

In [ ]:
esp=np.loadtxt("Speculation_Watch_List.csv",dtype=str,delimiter=',',usecols=(1,2,3,4,5))


Visualizamos las 10 primeras filas de los datos

In [ ]:
esp[0:10,]

array([['boro', 'block', 'lot', 'bbl', 'hnum_lo'],
       ['2', '3281', '45', '2032810045', '354'],
       ['2', '3281', '50', '2032810050', '366'],
       ['2', '2844', '105', '2028440105', '1459'],
       ['2', '2551', '8', '2025510008', '574'],
       ['3', '5625', '8', '3056250008', '914'],
       ['1', '2136', '60', '1021360060', '638'],
       ['3', '177', '34', '3001770034', '397'],
       ['4', '9236', '38', '4092360038', '84-43'],
       ['1', '1615', '11', '1016150011', '19']], dtype='<U23')

Ahora, vamos a ver qué dimensiones tiene el array para poder calcular posteriormente los estadísticos sin perder información.

In [ ]:
print(np.size(esp[0]))
print(np.size(esp[:,0]))

5
535


Creamos los arrays con las diferentes variables que nos interesan y las convertimos a numérico.

In [ ]:
boro=esp[1:536,0]
boro=boro.astype(np.int_)
print(boro[0:10])
block=esp[1:536,1]
block=block.astype(np.int_)
print(block[0:10])
lot=esp[1:536,2]
lot=lot.astype(np.int_)
print(lot[0:10])
bbl=esp[1:536,3]
bbl=bbl.astype(np.int_)
print(bbl[0:10])


[2 2 2 2 3 1 3 4 1 1]
[3281 3281 2844 2551 5625 2136  177 9236 1615  274]
[ 45  50 105   8   8  60  34  38  11  13]
[2032810045 2032810050 2028440105 2025510008 3056250008 1021360060
 3001770034 4092360038 1016150011 1002740013]


Calculamos los estadísticos que nos interesan.

In [ ]:
print(np.unique(boro))
print(np.mean(block))
print(np.var(lot))
print(np.min(bbl))
print(np.max(bbl))

[1 2 3 4 5]
3285.129213483146
4009.2696804556103
1001990031
5010050019
