In [ ]:
import numpy as np

Cargamos el dataset en un array de numpy

In [ ]:
doc=np.genfromtxt("50376.csv",dtype=str,delimiter=';')
doc

array([['\ufeffMunicipios', 'Fenómeno demográfico', 'Total'],
       ['07002 Alaior', 'nacidos vivos por residencia materna', '70'],
       ['07002 Alaior', 'muertes fetales tardías por residencia materna',
        '0'],
       ...,
       ['07065 Vilafranca de Bonany',
        'matrimonios por el lugar en que han fijado residencia', '7'],
       ['07065 Vilafranca de Bonany',
        'fallecidos por el lugar de residencia', '24'],
       ['07065 Vilafranca de Bonany', 'crecimiento vegetativo', '25']],
      dtype='<U53')

Vemos sus dimensiones

In [ ]:
print(np.size(doc[0]))
print(np.size(doc[:,0]))

3
336


Observamos que tiene 3 columnas y 336 filas. Ahora, vamos a mostrar las 10 primeras filas para ver qué tipo de datos son y si la primera fila son los nombres de las variables

In [ ]:
print(doc[0:10,])

[['\ufeffMunicipios' 'Fenómeno demográfico' 'Total']
 ['07002 Alaior' 'nacidos vivos por residencia materna' '70']
 ['07002 Alaior' 'muertes fetales tardías por residencia materna' '0']
 ['07002 Alaior' 'matrimonios por el lugar en que han fijado residencia'
  '27']
 ['07002 Alaior' 'fallecidos por el lugar de residencia' '64']
 ['07002 Alaior' 'crecimiento vegetativo' '6']
 ['07001 Alaró' 'nacidos vivos por residencia materna' '47']
 ['07001 Alaró' 'muertes fetales tardías por residencia materna' '0']
 ['07001 Alaró' 'matrimonios por el lugar en que han fijado residencia'
  '16']
 ['07001 Alaró' 'fallecidos por el lugar de residencia' '39']]


Vemos que la primera fila son los nombres de las variables y que dentro de Fenómeno demográfico hay 5 categorías por pueblo. 

In [ ]:
docnet=doc[1:336,].reshape(67,15)
print(docnet[0:5,])

[['07002 Alaior' 'nacidos vivos por residencia materna' '70'
  '07002 Alaior' 'muertes fetales tardías por residencia materna' '0'
  '07002 Alaior' 'matrimonios por el lugar en que han fijado residencia'
  '27' '07002 Alaior' 'fallecidos por el lugar de residencia' '64'
  '07002 Alaior' 'crecimiento vegetativo' '6']
 ['07001 Alaró' 'nacidos vivos por residencia materna' '47' '07001 Alaró'
  'muertes fetales tardías por residencia materna' '0' '07001 Alaró'
  'matrimonios por el lugar en que han fijado residencia' '16'
  '07001 Alaró' 'fallecidos por el lugar de residencia' '39'
  '07001 Alaró' 'crecimiento vegetativo' '8']
 ['07003 Alcúdia' 'nacidos vivos por residencia materna' '178'
  '07003 Alcúdia' 'muertes fetales tardías por residencia materna' '2'
  '07003 Alcúdia' 'matrimonios por el lugar en que han fijado residencia'
  '43' '07003 Alcúdia' 'fallecidos por el lugar de residencia' '108'
  '07003 Alcúdia' 'crecimiento vegetativo' '70']
 ['07004 Algaida' 'nacidos vivos por reside

Con el reshape, hemos conseguido tener todos los valores de cada variable en la misma columna, cosa que nos será muy útil para obtener sus valores más fácilmente.
Vamos a generar un vector con el crecimiento vegetativo, nacidos vivos por residencia materna y muertes fetales tardías por residencia materna.

In [ ]:
nvprm=docnet[:,2]
nvprm = nvprm.astype(np.float_)
mftprm=docnet[:,5]
mftprm=mftprm.astype(np.float_)
crecveg=docnet[:,14]
crecveg = crecveg.astype(np.float_)

print(nvprm[0:5])
print(mftprm[0:5])
print(crecveg[0:5])


[ 70.  47. 178.  58. 109.]
[0. 0. 2. 1. 1.]
[ 6.  8. 70.  6.  6.]


Vemos que hemos creado correctamente los array y hemos convertido a float sus valores, ahora calculamos algunos estadísticos sobre ellos.

In [ ]:
print(np.min(crecveg))
print(np.max(crecveg))
print(np.unique(mftprm))
print(np.mean(mftprm))

-42.0
119.0
[ 0.  1.  2.  3.  4. 16.]
0.5970149253731343
